---
language: node_js

node_js: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master

cache:
  directories:
  - node_modules

install: 
  - npm install

script:
  - npm run build
  - npm run deploy


branches:
  only:
    - master